from . import hospital_role
from . import hospital_specialization
from . import hospital_doctor_schedule
from . import res_partner
from . import hospital_appointment
from . import res_company
from . import res_config_settings
from . import appointment_cancel_wizard
from . import appointment_status
from . import todo